---
title: "Progrmación en R-Introducción"
author: "Santiago Lozano"
date: "11 de enero de 2020"
output:
  beamer_presentation:
    theme: "Darmstadt"
    colortheme: "default"
    fonttheme: "structurebold"
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## La Máquina Universal

- ¿Qué es exactamente una computadora?¿Cómo puede un dispositivo realizar gran cantidad de diferentes tareas?

- Un computador moderno puede definirse como "una máquina que almacena y manipula información bajo el control de programas cambiables"

## La Máquina Universal

- Esta definición puede ser vista desde dos           elementos claves.
  
    - Las computadoras son dispositivos para              manipular información (poner información y          transformarla en nueva )
    
        - Los computadores no son solo máquinas que           manipulan información (Calculadora, Bomba           de Gasolina), no son computadoras pues              están hechas para realizar una simple y             específica tarea
        
## La Máquina Universal

    - Las computadoras operan bajo el control de un       programa cambiable
    
        - Programa Computacional: Es un detallado,            paso a paso conjunto de intrucciones que            dicen a un computador exactamente que               hacer, si se cambia el programa, se cambia           el conjunto de acciones y se realiza una            tarea diferente, la máquina es la misma             pero el programa controla los cambios en            la máquina

## La Máquina Universal

Todo computador en sí es una máquina para ejecutar y realizar programas

## Potencia de los Programas

- El software controla el Hardware, pues determina lo que cualquier computador puede hacer.

-El proceso de crear software se denomina programación, es una habilidad que requiere destreza de manera integral y desarrolar aptitudes que no son para todo el mundo, sin embargo, se puede aprender en como programar computadores 

## ¿Qué es la ciencia de la computación (Computer Science)?

- Las ciencias de la Computación no son el estudio de los computadores

- El computador es a la Ciencia de la Computación lo que el Telescopio es a la Astronomía

- El computador es una herramienta importante en la ciencia de la computación, pues es es el que lleva a cab los procesos que podemos describir, pero el no es el objjeto de estudio

## ¿Qué es la ciencia de la computación (Computer Science)?

- La pregunta fundamental es ¿Qué proceso podemos describir? o mejor ¿Qué puede ser calculado?, existen numerosas técnica para resolver esta pregunta

- las 3 principales técnicas son el diseño, el análisis y la experimentación

- una manera de demostrar que un problema particular puede ser demostrado es diseñando una solución, es de cir un proceso paso a paso para lograr el resultado deseado, esto se denomina un algoritmo que es una manera elegante de deir una receta, el diseño de algoritmos es una parte muy importente en el computer science

## ¿Qué es la ciencia de la computación (Computer Science)?

- una debilidad del diseño es que uno puede responder la pregunta ¿Qué es calculable?, pues si uno diseña un algoritmo que resuelve el problema acabó, pero si uno no puede diseñar un algoritmo, no necesariamente quiere decir que el problema no tiene solución.(puede que no haya logrado usted la respuesta)Aquí viene el análisis

- El análisis es el proceso de examinar algoritmos y problemas matemáticamentes, por ejemplo, mediante el análisis podemos mostrar que problemas aparentemente simple no se pueden resolver por algún algoritmo, o también podemos comprobar que mediante el análisis los problemas son muy largo y requieren mucha memoria

## ¿Qué es la ciencia de la computación (Computer Science)?

- Cuando los problemas son bastante complejos o no definidos en un marco de análisis, la experimentación se convierte en un arma confiable, ellos se encargan de implementar sisitemas y entonces estudiar el comportamiento resultante. incluso cuando un análisi teórico se realiza la experimentación es necesaria para verificar y refinar ese análisi

- En la mayoría de problemas existe una línea para saber si un sistema funcional y confiable puede ser construído, a menudo una prueba empírica es requerida en el sistema para determinar si ese umbral ha sido cruzado

## ¿Qué es la ciencia de la computación (Computer Science)?

- Esto desde una perspectiva académica, pero hoy en día las ciencias de la computación envuelven mucho aspectos como redes, interación humano.computador, inteligencia artificial, bases de datos, ingeniería de software, etc

## Cosas Básicas sobre el Hardware

-Aprender detalles sobre como funciona un computador nos harán mejores programadores, no es algo necesario, pero, ayuda a dominar el paso que seguimos para poner nuestros programas en acción, es como un auto, saber un poco sobre la parte mecánica ayuda a mejorar el rendimiento de este a la hora de conducir, aunque se puede aprender sin este paso

-A pesar de que diferentes computadores pueden variar significativamente en detalles específicos, en su mayoría todos los computadores modernos son remarcablemente similares

- Primeramente mencionamos la CPU (Central processing unit) la cual es el "cerebro de la máquina", es donde todas las operaciones básicas del computador se llevan a cabo. La CPU puede realizar operaciones aritméticas simples, como sumar dos números y puede llevar a cabo operaciones lógicas como ver si dos números son igúales

- La memoria almacena programas y datos. La CPU puede solo acceder directamente a información que está almacenada en la memoria principal (Memoria RAM (Random Access Memory)), esta memoria es rápida pero es también volátil, es decir, si el computador se llega a apagar la información en la memoria se pierde

- Con esto debe existir una memoria secundaria que dé almacenamiento permanente, en un computador moderno, es usual encontrar algún tipo de medios magnéticos como disco duro (hard drive), medios óptico como CD (Compact disc) y DVD (Digital Versatile Disc) y memorias flash como memoria "USB" (stick memory)

- los humanos interactuan con el computador a través de dispositivos de entrada y salida, dispositivos como el mouse, teclado son dispositivos de entrada, cuya información de estos dispositivos es procesada por la CPU y puede ser enviada a la memoria principal o secundaria. Similarmente, cuando la información necesita ser desplegada, la CPU envía la información a uno o más dispositivos de salida.

- Entonces cuando se quiere quemar o poner en marcha su juego favorito o procesamiento de palabras; primero, las instrucciones que comprenden el programa son copiadas de la memoria permanente a la memoria principal del computador. una vez la instrucción es cargada, la CPU comienza a ejecutar el programa

- Tecnicamente la CPU sigue un proceso llamado ciclo Búsqueda-ejecución (fetch-execute cycle). La primera instrucción es recuperada de la memoria, descifrada para descubrir lo que representa y la acción apropiada es llevada a cabo. Entonces la siguiente instrucción es traída, decodificada y ejecutada. El ciclo continua instrucción tras instrucción. Esto es realmente lo que hace un computador desde que se enciende hasta que se apaga, para algo trivial pero la velocidad y la cantidad de millones de instrucciones que mueve la memoria cada segundo es impresionanante 

## Lenguajes de Programación

- Recordando que un programa es solo una secuencia de instrucciones que le dicen a un computador que hacer. Obviamente, necesitamos proveer esas instrucciones en un lenguaje que el computador puede entender. Sería genial si se pudiera indicarle a un computador usando el lenguaje nativo pero a pesar de los esfuerzo, diseñar un computador que pueda entender el lenguaje humano es una tarea sin solución, pues el lenguaje natural es tenso con ambiguedades e imprecisiones

- Las científicos en computación han conseguido alrededor de este problema diseñar notaciones para experesar cálculos en una vía exacta y sin ambiguedades. Estas notaciones especiales son llamadas lenguajes de programación

- Toda estructura en un leguaje de programación tiene una forma precisa (sintaxis) y un significado preciso (semántica)

- Un lenguaje de programación es algo así como un código para escribir hacia abajo las instrucciones que un computador seguirá 

- Los programadores se refieren a menudo a sus programam como un código de computadora

- y el proceso de escribir un algoritmo en un leguaje de progrmación se denomina codificar

- R es un ejemplo de un lenguaje de programación y el que veremos durante todo el curso

- Existen otro tipo de lenguaje como Python, Java, C++, Fortran, Basic. Los cuales poseen diferente características pero comparten la característica de estar bien definidos, sintaxis y semántica no ambiguas

- los lenguajes mencionados anteriormente son ejemplos de lenguajes de alto nivel, los cuales, además de ser precisos, son diseñados para ser usados y entendido por humanos

- El hardware computacional puede solo entender un muy lenguaje de bajo de nivel conocido como lenguaje de máquina

- Suponga que queremos que el computador sume dos números. La instrucción que la CPU lleva a cabo realmente puede ser algo como

  - cargue el número desde la ubicación 2001 en          memoria a la CPU

  - cargue el número desde la ubicación 2002 en          memoria a la CPU
  
  - sume los dos números en la CPU
  
  - Almacene los dos números en la ubicación 2003
  
Parece ser mucho trbajo sumar dos número, es más, puede ser más complicado sabiendo que la instrucción y los números son representados en notación binaria

- En un lenguaje de alto nivel la suma de dos números se puede hacer de una simple manera c = a + b que es más fácil de entender, pero necesitamos transladar esto a un lenguaje de máquina que el computador pueda ejecutar, para esto disponemos de dos maneras compilar o interpretar

- Un compilador es un programa de computadora complejo que toma otro programa escrito en alto nivel y lo traduce a un equivalente programa en lenguaje de máquina de algún computador 

- Un interpetador es un programa que simula una computadora que entiende un leguaje de alto nivel. En vez de traducir, el programa fuente a lenguaje de máquina equivalente, el interpretador analiza y ejecuta la instrucción de código fuente instrucción por instrucción cuante veces sea necesario

- La diferencia entre interpretador y compilador es que un compilador es una traducción de un tiro, una vez el programa es compilado, este puede ser corrido una y otra vez sin más trabajo del compilador o el código fuente. En el caso de un interpretador, la interpretación y el código fuente son necesarias cada vez que se corre el programa

- los programas compilados tienden a ser más rápidos, pero los lenguajes interpretados tienden a si mismos a tener un ambiente de programamción más flexible, como programa que pueden ser desarrollados y corridos interactivamente

- otra ventaja en los programas de alto nivel es su portabilidad y es que estos puede correr en cualquier CPU, contrario a los lenguajes de máquina los cuales pueden ser corrido para CPU de sus respectivos fabricantes

## Introducción a R (Definición)

- De esta manera, R es un leguaje de alto nivel y un ambiente de trabajo para el análisi de datos y gráficos, este posee un intérprete el cual ejecuta el código que le demos, a diferencia de lenguajes como Java, C o C++ los cuales deben compilar primero su código, aunque en algunos Códigos exigentes son escritos en C o C++.

## Introducción a R (Origen)

- R fue creado por Ross Ihaka y Robert Gentleman, el cual es un clon del software S-Plus que fue creado en 1988

## ¿Por qué usar R?

- Primero que todo R es Gratis y es de código abierto, es decir, es un proyecto colaborativo y abierto donde los usuarios pueden definir sus propias funciones, aparte de numerosas biblioteca preconstruidas que tiene, también se pueden publicar paquetes que puede extender su configuración básica

- Es posible que algoritmos computacionalmente exigentes pueden ser desarrollados en C, C++ o Fortran y vincularlos directamente con R

- Al ser un lenguaje que contiene interpretador posee variedad de ambientes de trabajo como R Studio, R Commander, Tinn R y el ambiente predeterminado que permiten una amigabilidad a la hora de manejar códigos y datos